#!/bin/csh -f
# file: setup_2models
# Creates the meeded subdirectories and html files for comparison
# of two model runs.
# First command line argument is model1 name
# Second command line argument is model2 name
# Third command line argument is the image type

set HTML = $HTML_HOME/model1-model2
echo "value of mg micro var: $MG_MICRO"

#----------------------------------------------------------------
if ($#argv != 3) then
  echo "usage: setup_models <model1> <model2> <gif,jpg,png>"
  exit
endif
# create the needed subdirectories

if (! -e set1) mkdir set1
if (! -e set2) mkdir set2
if (! -e set3) mkdir set3
if (! -e set4) mkdir set4
if (! -e set4a) mkdir set4a
if (! -e set5_6) mkdir set5_6
if (! -e set7) mkdir set7
if (! -e set8) mkdir set8
if (! -e set9) mkdir set9
if (! -e set10) mkdir set10 
if (! -e set11) mkdir set11 
if (! -e set12) mkdir set12 
if (! -e set13) mkdir set13 
if (! -e set14) mkdir set14
if (! -e set15) mkdir set15
if (! -e set16) mkdir set16
if (! -e wset1) mkdir wset1
if (! -e cset1) mkdir cset1
if (! -e cset2) mkdir cset2
if (! -e cset3) mkdir cset3
if (! -e cset4) mkdir cset4
if (! -e cset5) mkdir cset5
if (! -e cset6) mkdir cset6
if (! -e cset7) mkdir cset7
if (! -e images) mkdir images

cp $DIAG_HOME/html/images/* images/
cp $HTML/sets*.htm .
cp $HTML/set1/set1*.htm set1/
cp $HTML/set2/set2*.htm set2/
cp $HTML/set3/set3*.htm set3/
cp $HTML/set4/set4*.htm set4/
cp $HTML/set4a/set4a*.htm set4a/
cp $HTML/set5_6/set5_6*.htm set5_6/
cp $HTML/set7/set7*.htm set7/
cp $HTML/set8/set8*.htm set8/
cp $HTML/set9/set9*.htm set9/
cp $HTML/set10/set10*.htm set10/
cp $HTML/set11/set11*.htm set11/
cp $HTML/set12/set12*.htm set12/
cp $HTML/set13/set13*.htm set13/
cp $HTML/set14/set14*.htm set14/
cp $HTML/set15/set15*.htm set15/
cp $HTML/set16/set16*.htm set16/
cp $HTML/wset1/wset1*.htm wset1/
cp $HTML/cset1/cset1*.htm cset1/
cp $HTML/cset2/cset2*.htm cset2/
cp $HTML/cset3/cset3*.htm cset3/
cp $HTML/cset4/cset4*.htm cset4/
cp $HTML/cset5/cset5*.htm cset5/
cp $HTML/cset6/cset6*.htm cset6/
cp $HTML/cset7/cset7*.htm cset7/

# contruct new file with model name
# SETS top level
if (-e sets.htm) then
  rm sets.htm
endif
cp sets_1.htm sets.htm
sed 's/test_ctrl_runs/'$1'<br>and<br> '$2'/' sets.htm > temp.htm && /bin/mv temp.htm sets.htm
echo '<b>Plots Created </b><br>' >> sets.htm
echo `date` >> sets.htm
cat sets_2.htm >> sets.htm
if (-e index.html) /bin/rm index.html
ln -s sets.htm index.html
# SET1
if (-e set1/set1.htm) then
  rm set1/set1.htm
endif
cp set1/set1_1.htm set1/set1.htm
echo $1 "<br>and<br>" $2 >> set1/set1.htm
cat set1/set1_2.htm >> set1/set1.htm
# SET2
if (-e set2/set2.htm) then
  rm set2/set2.htm
endif
cp set2/set2_1.htm set2/set2.htm
echo $1 "<br>and<br>" $2 >> set2/set2.htm
cat set2/set2_2.htm | sed -e s/xxx/$3/ >> set2/set2.htm
# SET3
if (-e set3/set3.htm) then
  rm set3/set3.htm
endif
cp set3/set3_1.htm set3/set3.htm
echo $1 "<br>and<br>" $2 >> set3/set3.htm
cat set3/set3_2.htm | sed -e s/xxx/$3/ >> set3/set3.htm
# SET4
if (-e set4/set4.htm) then
  rm set4/set4.htm
endif
cp set4/set4_1.htm set4/set4.htm
echo $1 "<br>and<br>" $2 >> set4/set4.htm
if($MG_MICRO == "0")then
 cat set4/set4_3.htm | sed -e s/xxx/$3/ >> set4/set4.htm
else
 cat set4/set4_2.htm | sed -e s/xxx/$3/ >> set4/set4.htm
endif
# SET4a
if (-e set4a/set4a.htm) then
  rm set4a/set4a.htm
endif
cp set4a/set4a_1.htm set4a/set4a.htm
echo $1 "<br>and<br>" $2 >> set4a/set4a.htm
cat set4a/set4a_2.htm | sed -e s/xxx/$3/ >> set4a/set4a.htm
# SET5_6
if (-e set5_6/set5_6.htm) then
  rm set5_6/set5_6.htm
endif
cp set5_6/set5_6_1.htm set5_6/set5_6.htm
echo $1 "<br>and<br>" $2 >> set5_6/set5_6.htm
if($MG_MICRO == "0")then
 cat set5_6/set5_6_3.htm | sed -e s/xxx/$3/ >> set5_6/set5_6.htm
else
 cat set5_6/set5_6_2.htm | sed -e s/xxx/$3/ >> set5_6/set5_6.htm
endif
# SET7
if (-e set7/set7.htm) then
  rm set7/set7.htm
endif
cp set7/set7_1.htm set7/set7.htm
echo $1 "<br>and<br>" $2 >> set7/set7.htm
cat set7/set7_2.htm | sed -e s/xxx/$3/ >> set7/set7.htm
# SET8
if (-e set8/set8.htm) then
  rm set8/set8.htm
endif
cp set8/set8_1.htm set8/set8.htm
echo $1 "<br>and<br>" $2 >> set8/set8.htm
cat set8/set8_2.htm | sed -e s/xxx/$3/ >> set8/set8.htm
# SET9
if (-e set9/set9.htm) then
  rm set9/set9.htm
endif
cp set9/set9_1.htm set9/set9.htm
echo $1 "<br>and<br>" $2 >> set9/set9.htm
cat set9/set9_2.htm | sed -e s/xxx/$3/ >> set9/set9.htm
# SET10 
if (-e set10/set10.htm) then
  rm set10/set10.htm 
endif
cp set10/set10_1.htm set10/set10.htm
echo $1 "<br>and<br>" $2 >> set10/set10.htm
cat set10/set10_2.htm | sed -e s/xxx/$3/ >> set10/set10.htm
# SET11 
if (-e set11/set11.htm) then
  rm set11/set11.htm 
endif
cp set11/set11_1.htm set11/set11.htm
echo $1 "<br>and<br>" $2 >> set11/set11.htm
cat set11/set11_2.htm | sed -e s/xxx/$3/ >> set11/set11.htm
# SET12 
if (-e set12/set12.htm) then
  rm set12/set12.htm 
endif
cp set12/set12_1.htm set12/set12.htm
echo $1 "<br>and<br>" $2 >> set12/set12.htm
cat set12/set12_2.htm | sed -e s/xxx/$3/ >> set12/set12.htm
# SET13 
if (-e set13/set13.htm) then
  rm set13/set13.htm 
endif
cp set13/set13_1.htm set13/set13.htm
echo $1 "<br>and<br>" $2 >> set13/set13.htm
cat set13/set13_2.htm | sed -e s/xxx/$3/ >> set13/set13.htm
# SET14
cp set14/set14_1.htm set14/set14.htm
echo $1 "<br>and<br>" $2 >> set14/set14.htm
cat set14/set14_2.htm | sed -e s/xxx/$3/ >> set14/set14.htm
# SET15
cp set15/set15_1.htm set15/set15.htm
echo $1 "<br>and<br>" $2 >> set15/set15.htm
cat set15/set15_2.htm | sed -e s/xxx/$3/ >> set15/set15.htm

# SET16
cp set16/set16_1.htm set16/set16.htm
echo $1 "<br>and<br>" $2 >> set16/set16.htm
cat set16/set16_2.htm | sed -e s/xxx/$3/ >> set16/set16.htm

foreach col (EPIC SGP)
 cp set16/set16_1.htm set16/set16_{$col}.htm
 echo $1 "<br>and<br>" $2 >> set16/set16_{$col}.htm
 cat set16/set16_3.htm | sed -e s/xxx/$3/  | sed -e s/lll/$col/ >> set16/set16_{$col}.htm
end

# WSET1
if (-e wset1/wset1.htm) then
  rm wset1/wset1.htm
endif
cp wset1/wset1_1.htm wset1/wset1.htm
echo $1 "<br>and<br>" $2 >> wset1/wset1.htm
cat wset1/wset1_2.htm | sed -e s/xxx/$3/ >> wset1/wset1.htm

# CSET1
if (-e cset1/cset1.htm) then
  rm cset1/cset1.htm
endif
cp cset1/cset1_1.htm cset1/cset1.htm
echo $1 "<br>and<br>" $2 >> cset1/cset1.htm
cat cset1/cset1_2.htm | sed -e s/xxx/$3/ >> cset1/cset1.htm
# CSET2
if (-e cset2/cset2.htm) then
  rm cset2/cset2.htm
endif
cp cset2/cset2_1.htm cset2/cset2.htm
echo $1 "<br>and<br>" $2 >> cset2/cset2.htm
cat cset2/cset2_2.htm | sed -e s/xxx/$3/ >> cset2/cset2.htm
# CSET3
if (-e cset3/cset3.htm) then
  rm cset3/cset3.htm
endif
cp cset3/cset3_1.htm cset3/cset3.htm
echo $1 "<br>and<br>" $2 >> cset3/cset3.htm
cat cset3/cset3_2.htm | sed -e s/xxx/$3/ >> cset3/cset3.htm
# CSET4
if (-e cset4/cset4.htm) then
  rm cset4/cset4.htm
endif
cp cset4/cset4_1.htm cset4/cset4.htm
echo $1 "<br>and<br>" $2 >> cset4/cset4.htm
cat cset4/cset4_2.htm | sed -e s/xxx/$3/ >> cset4/cset4.htm
# CSET5
if (-e cset5/cset5.htm) then
  rm cset5/cset5.htm
endif
cp cset5/cset5_1.htm cset5/cset5.htm
echo $1 "<br>and<br>" $2 >> cset5/cset5.htm
cat cset5/cset5_2.htm | sed -e s/xxx/$3/ >> cset5/cset5.htm
# CSET6
if (-e cset6/cset6.htm) then
  rm cset6/cset6.htm
endif
cp cset6/cset6_1.htm cset6/cset6.htm
echo $1 "<br>and<br>" $2 >> cset6/cset6.htm
cat cset6/cset6_2.htm | sed -e s/xxx/$3/ >> cset6/cset6.htm
# CSET7
if (-e cset7/cset7.htm) then
  rm cset7/cset7.htm
endif
cp cset7/cset7_1.htm cset7/cset7.htm
echo $1 "<br>and<br>" $2 >> cset7/cset7.htm
cat cset7/cset7_2.htm | sed -e s/xxx/$3/ >> cset7/cset7.htm

