#! /bin/csh

#PBS -N ocn_diags
#PBS -q short
#PBS -l walltime=01:00,nodes=1:ppn=16
#PBS -r n
#PBS -S /bin/csh -V
#PBS -j oe

module load lang/python/2.7.7
module load tool/nco/default

set sdate = `date +"%Y-%m-%d_%H:%M:%S"`
cd /home/aliceb/sandboxes/cesm1_3_alpha18a_newtesting/postprocessing/diagnostics/ocn

#mpiexec -info
mpiexec ./ocn_diags_wrapper.py --caseroot ~/sandboxes/runs/b.e13.B1850C5CN.f19_g16.01 >& ocn_diags.$sdate.log

#mpiexec ./hello.py

echo "ocn_diags.run ended $sdate"

