#!/usr/bin/env python
"""read the xml files and set the environment needed for standalone NCL testing

__________________________
Created on October, 2015

Author: CSEG <cseg@cgd.ucar.edu>
"""

from __future__ import print_function

import sys

# check the system python version and require 2.7.x or greater
if sys.hexversion < 0x02070000:
    print(70 * "*")
    print("ERROR: {0} requires python >= 2.7.x. ".format(sys.argv[0]))
    print("It appears that you are running python {0}".format(
            ".".join(str(x) for x in sys.version_info[0:3])))
    print(70 * "*")
    sys.exit(1)

#
# built-in modules
#
import argparse
import os
import re
import stat

#
# activate the virtual environment that was created by create_python_env.sh
#
if ( not os.path.isfile('./cesm-env2/bin/activate_this.py') ):
    err_msg = ('set_env ERROR: the virtual environment cesm-env2 does not exist.' \
               'Please run $POSTPROCESSING_PATH/create_python_env.sh [-machine_dir [machine directory]] -machine [machine name]')
    raise OSError(err_msg)

execfile('./cesm-env2/bin/activate_this.py', dict(__file__='./cesm-env2/bin/activate_this.py'))

try:
    import lxml.etree as etree
except:
    import xml.etree.ElementTree as ET

re_val = re.compile(r'\$(\{([A-Za-z0-9_]+)\}|[A-Za-z0-9_]+)')

#
# import modules installed in the virtual environment
#
from diag_utils import diagUtilsLib

# -------------------------------------------------------------------------------
# commandline_options - parse any command line options
# -------------------------------------------------------------------------------

def commandline_options():
    """Process the command line arguments.

    """
    parser = argparse.ArgumentParser(
        description='Read the caseroot postprocessing XML files and set the local environment for debugging')

    parser.add_argument('-component', '--component', choices=['atm','ice','lnd','ocn'], required=True, nargs=1,
                        help='select a component [atm, ice, lnd, ocn] to set the environment using the associated XML file')

    parser.add_argument('-shell', '--shell', choices=['bash','csh'], required=True, nargs=1,
                        help='select a shell [bash, csh] to create a file that can be sourced')

    parser.add_argument('-backtrace', '--backtrace', action='store_true',
                        help='show exception backtraces as extra debugging output')

    parser.add_argument('-debug', '--debug', nargs=1, required=False, type=int, default=0,
                        help='debugging verbosity level output: 0 = none, 1 = minimum, 2 = maximum. 0 is default')

    parser.add_argument('-caseroot', '--caseroot', nargs=1, required=True, 
                        help='fully quailfied path to case root directory')

    options = parser.parse_args()
        
    return options

#==============================================================================
# expand recursive function
#==============================================================================
def expand (val, src):
  """
  Recursively traverse the environment dictionary to expand all environment variables
  
  Arguments
  val (string) - value to be expanded
  src (dictionary) -  source dictionary to search and resolve param val

  Return
  expanded value
  """
  return re_val.sub(lambda m: expand(src.get(m.group(1), ''), src), val)

#==============================================================================
# readXML - read and resolve an XML input file against a source directory
#==============================================================================
def readXML(casedir, env_file_list):
  """
  for the <entry id=value> xml files in casedir/env_file_list,
  returns a dictionary output["id"]="value"

  Arguments:
  casedir (string) - case root directory
  env_file_list - list of env_*.xml files to parse in the casedir

  Return:
  output (dictionary) 
  """
  output = dict()
  for efile in env_file_list:
    env_file = '{0}/{1}'.format(casedir, efile)
    if os.path.isfile(env_file):
      xml_tree = ET.ElementTree()
      xml_tree.parse(env_file)
      for entry_tag in xml_tree.findall('entry'):
        output[entry_tag.get('id')] = entry_tag.get('value')
    else:
      err_msg = 'cesmEnvLib.readXML ERROR: {0} does not exist or cannot be read'.format(env_file)
      raise TypeError(err_msg)

  # expand nested environment variables
  for k,v in output.iteritems():
    output[k] = expand(v, output)

  # remove () in output dictionary values
  for k,v in output.iteritems():
    output[k] = re.sub('[()]', '', v)
    
  return output


# -------------------------------------------------------------------------------
# main
# -------------------------------------------------------------------------------
def main(options):
    """ main
    """
    envDict = dict()

    caseroot = options.caseroot[0]
    prefix_map = {'atm':'ATMDIAG_',
                  'ice':'ICEDIAG_',
                  'lnd':'LNDDIAG_',
                  'ocn':'OCNDIAG_'}

    prefix = prefix_map[options.component[0]]

    compEnvFile = 'env_diags_{0}.xml'.format(options.component[0])

    envFiles = ['env_postprocess.xml', compEnvFile]

    envDict = readXML(caseroot, envFiles)

    envDict = diagUtilsLib.strip_prefix(envDict, prefix)

    filename = 'set_env_{0}'.format(options.component[0])
    first = True
    if options.shell[0] == 'csh':
        filename = '{0}.csh'.format(filename)
    else:
        filename = '{0}.sh'.format(filename)
    
    with open (filename, 'w') as envFile:
        for key, value in envDict.iteritems():
            tmpvalue = None
            if 'PATH' in key:
                tmpvalue = os.getenv(key)

            if options.shell[0] == 'csh':
                if tmpvalue is not None:
                    line = 'setenv {0} {1}:{2}\n\n'.format(key, value, tmpvalue)
                else:
                    line = 'setenv {0} {1}\n\n'.format(key, value)
                if first:
                    instruct = 'Be sure to run "source ./{0}"'.format(filename)
                    first = False
            else:
                if tmpvalue is not None:
                    line = 'set {0}={1}:{2}\n'.format(key, value, tmpvalue) + 'export {0}\n\n'.format(key)
                else:
                    line = 'set {0}={1}\n'.format(key, value) + 'export {0}\n\n'.format(key)
                if first:
                    instruct = 'Be sure to run "./{0}"'.format(filename)
                    first = False

            envFile.write(line)

    st = os.stat(filename)
    os.chmod(filename, st.st_mode | stat.S_IEXEC)

    return 'Successfully created {0}. {1}'.format(filename, instruct)
    
    
#===================================

if __name__ == "__main__":
    options = commandline_options()
    try:
        status = main(options)
        sys.exit(status)
    except Exception as error:
        print(str(error))
        sys.exit(1)
