#!/usr/bin/env python
"""print the machine name from the hostname

__________________________
Created on October, 2015

Author: CSEG <cseg@cgd.ucar.edu>
"""

from __future__ import print_function

import sys

# check the system python version and require 2.7.x or greater
if sys.hexversion < 0x02070000:
    print(70 * "*")
    print("ERROR: {0} requires python >= 2.7.x. ".format(sys.argv[0]))
    print("It appears that you are running python {0}".format(
            ".".join(str(x) for x in sys.version_info[0:3])))
    print(70 * "*")
    sys.exit(1)

#
# built-in modules
#
import os

#
# check the POSTPROCESS_PATH which must be set
#
try:
    os.environ["POSTPROCESS_PATH"]
except KeyError:
    err_msg = ('create_postprocess ERROR: please set the POSTPROCESS_PATH environment variable.' \
               ' For example on yellowstone: setenv POSTPROCESS_PATH /glade/p/cesm/postprocessing')
    raise OSError(err_msg)

cesm_pp_path = os.environ["POSTPROCESS_PATH"]

#
# activate the virtual environment that was created by create_python_env
#
if not os.path.isfile('{0}/cesm-env2/bin/activate_this.py'.format(cesm_pp_path)):
    err_msg = ('create_postprocess ERROR: the virtual environment cesm-env2 does not exist.' \
               ' Please run $POSTPROCESS_PATH/create_python_env -machine [machine name]')
    raise OSError(err_msg)

execfile('{0}/cesm-env2/bin/activate_this.py'.format(cesm_pp_path), dict(__file__='{0}/cesm-env2/bin/activate_this.py'.format(cesm_pp_path)))

#
# import modules installed in the virtual environment
#
from cesm_utils import cesmEnvLib


# -------------------------------------------------------------------------------
# main
# -------------------------------------------------------------------------------
def main():
    """ main
    """
    # set some variables
    machine = None
    hostname = cesmEnvLib.get_hostname()

    machine = cesmEnvLib.get_machine_name(hostname, '{0}/Machines/machine_postprocess.xml'.format(cesm_pp_path))

    if machine is None:
        message = "Could not identify machine from host name and machines_postprocess.xml config file.\n"
        message += "    hostname = {0}\n".format(hostname)
        raise RuntimeError(message)

    return machine
    
    
#===================================

if __name__ == "__main__":
    try:
        machine = main()
        print("{0}".format(machine))
    except Exception as error:
        print(str(error))
        sys.exit(1)
