#!/usr/bin/env python 

import pprint
import pkg_resources

installed_packages = [d for d in pkg_resources.working_set]
installed_packages_list = sorted(["%s==%s" % (i.key, i.version) for i in installed_packages])
pp = pprint.PrettyPrinter(indent=5)
pp.pprint(installed_packages_list)
