#!/bin/bash -l

echo "Python boot-strap modules for machine cheyenne"

module load python/2.7.16
module load intel/17.0.1
module load ncarenv
module load ncarcompilers
module load mpt/2.19
module load netcdf/4.6.3
module load nco/4.7.9
module load ncl/6.6.2

# clone the ncat virtualenv first with helper script ncar_pylib
# use "ncar_pylib --help" to see all options
ncar_pylib -c 20190627 ${pp_dir}/cesm-env2

export PYTHONPATH=${pp_dir}/cesm-env2/lib/python2.7/site-packages

module list

