#!/bin/bash -l

echo "Python boot-strap modules for NCAR DAV"

module load python/2.7.16
module load gnu/8.3.0
module load ncarenv
module load ncarcompilers
module load openmpi/3.1.4
module load netcdf/4.7.1
module load nco/4.7.4
module load ncl/6.6.2 

# clone the ncat virtualenv first with helper script ncar_pylib
# use "ncar_pylib --help" to see all options
ncar_pylib -c 20191031 ${pp_dir}/cesm-env2

export PYTHONPATH=${pp_dir}/cesm-env2/lib/python2.7/site-packages

module list

