#!/bin/sh -x

echo "Python boot-strap modules for machine edison"
. /opt/modules/default/init/sh

module load python/2.7.9
module load virtualenv/12.1.1
module load numpy/1.9.2
module load scipy/0.15.1
module load mpi4py/1.3.1
#module load pynio/1.4.1
module load matplotlib/1.4.3
module load nco/4.3.9
module load ncl/6.1.1
module load cray-netcdf/4.3.2
module load cray-hdf5/1.8.13

# make sure the intel environment is loaded
module swap PrgEnv-gnu PrgEnv-intel 

# create the ocn_diag/eco_lib/remap.so shared library
f2py -c --fcompiler=intelem --f77exec=/opt/intel/composer_xe_2015.1.133/bin/intel64/ifort -m ../ocn_diag/eco_lib/remap ../ocn_diag/eco_lib/remap.f

# may need basemap for ocn ecosys

module list

