#!/bin/sh

echo "Python boot-strap modules for machine yellowstone"
. /glade/apps/opt/lmod/lmod/init/bash

module unload all-python-libs

module load python/2.7.7
module load numpy/1.8.1
module load scipy/0.15.1
module load mpi4py/2.0.0
module load pynio/1.4.1
module load matplotlib/1.4.3
module load intel/12.1.5
module load netcdf/4.3.0
module load nco/4.4.4
module load ncl/6.3.0

# prepend the virtualenv into the PATH
PATH=/glade/apps/contrib/virtualenv/12.0.7:${PATH}
export PATH

# may need basemap for ocn ecosys

module list

