#!/usr/bin/env bash
#
# template to activate the virtualenv, call post process program, deactivate virtualenv
#

#PBS -N ration
#PBS -q regular
#PBS -l select=1:ncpus=8:mpiprocs=8
#PBS -l walltime=00:00:02
#PBS -A P93300606

source /etc/profile.d/modules.sh

export MPI_UNBUFFERED_STDIO=true
export TMPDIR=$TMPDIR

#module purge

## activate the virtualenv that contains all the non-bootstrapped dependencies
cd $POSTPROCESS_PATH/cesm-env2/bin
echo "Running from virtualenv directory:"
pwd
. activate

## load the boot-strap modules
#module load gnu/8.3.0
#module load ncarenv
#module load ncarcompilers
#module load mpt/2.19

mpiexec_mpt dplace -s 1 $POSTPROCESS_PATH/Tools/ration_test.py >> $POSTPROCESS_PATH/Tools/ration.log

status=$?
echo $status

deactivate

echo $status
