#!/bin/bash -l

## test the mpi4py and ASAPPyTools utility on geyser with ncar_pylib virtualenv 

#SBATCH -t 00:05:00
#SBATCH -n 4
#SBATCH -N 2
#SBATCH --ntasks-per-node=2
#SBATCH -p dav
#SBATCH -J ration_test
#SBATCH -A P93300606
#SBATCH -C geyser
#SBATCH --mem 1G
#SBATCH -e ration_test.err.%J
#SBATCH -o ration_test.out.%J

export MP_LABELIO=yes

module load python/2.7.14

. /glade2/work/aliceb/sandboxes/dev/postprocessing_geyser/cesm-env2/bin/activate

srun ./ration_test.py >> ./ration.log

status=$?
echo $status

deactivate

echo $status




